#!/bin/bash

_return=false;
#Define command-level options
_args=("--start" "--stop" "--restart" "--deploy");
_port=50001;

#Start it
startParam()
{
    # Configurable options
    _command="ng serve --environment=dev --aot --host web.discoexample.dev.scmnight.com --port $_port";
    _needsCommandUp=false;
    _canExecute() {
        _print "Starting server...";
        mkdir -p /var/www/logs/scripts/ && touch /var/www/logs/scripts/web.discoexample.dev.scmnight.com.log && cd /var/www/html/discoexample.dev.scmnight.com/web && nohup $_command &>/var/www/logs/scripts/web.discoexample.dev.scmnight.com.log &
        _print "Server started!" "green";
        _print "NOTE: Angular is still loading." "yellow";
        _print "Log file: /var/www/logs/scripts/web.discoexample.dev.scmnight.com.log" "black" "green";
        _return=true;
    }
    _cantExecute() {
        _print "Angular for web.discoexample.dev.scmnight.com already running!" "white" "red";
        _print "TIP: Use scm-dev-web-disco --stop to stop the server." "cyan";
        _print "TIP: Use scm-dev-web-disco --restart to restart the server." "cyan";
        _return=false;
    }
    # START SCM COMMAND
    source scm-execute
}

# Stop it
stopParam()
{
    # Configurable options
    _command="netstat -nlp | grep :$_port";
    _needsCommandUp=true;
    _canExecute() {
        _print "Stopping server...";
        _success="$(fuser -n tcp -k $_port)";
        if [ $_success ]
        then
            _print "Server stopped!" "green";
        else
            _print "Server could not be stopped" "red";
        fi
        _return=true;
    }
    _cantExecute() {
        _print "Angular for web.discoexample.dev.scmnight.com is not running!" "white" "red";
        _print "TIP: Use scm-dev-web-disco --start to start the server." "cyan";
        _return=false;
    }
    # START SCM COMMAND
    source scm-execute
}

# Restart it
restartParam() {
    stopParam=$(stopParam);
    if [ "$_return" == "true" ]
    then
        _print "Doing restart proccess!" "blue" "white";
        startParam;
    else
        _print "Cannot restart web.discoexample.dev.scmnight.com. It is not running." "red";
        _print "TIP: Use scm-dev-web-disco --start to start the server." "cyan";
    fi

}

#Deploy it
deployParam() {
    _print "Start packing and doing stuff..." "blue" "white";
    mkdir -p "/var/www/html/api.scmnight.com/projects/disco-panel-web/";
    ng build --delete-output-path --build-optimizer --progress --verbose --aot --prod --env=prod --target=production --environment=prod --output-path="/var/www/html/api.scmnight.com/projects/disco-panel-web/";
    _print "Proccess finished! Check details above." "blue" "white";
}

# GET SOURCES
source scm-core